# TASK 3

 Day 14. Task 03
Метрики
 0. Импорты

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

Загрузите снова тот же датафрейм, как и в прошлом задании.Воспользуйтесь train_test_split с параметрами test_size=0.2, random_state=21 и получите X_train, y_train, X_test, y_test.
Используйте дополнительный параметр stratify.

In [3]:
df = pd.read_csv('C:\\Google Drive\\School21\\Day14\\day-of-week-not-scaled.csv')

In [4]:
df

,numTrials,hour,dayofweek,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,...,labname_lab02,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1
0,1,5,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2,5,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,3,5,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4,5,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,5,5,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1681,9,20,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1682,6,20,3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1683,7,20,3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1684,8,20,3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1685,9,20,3,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [5]:
X = df.drop(columns = ['dayofweek'])
X

,numTrials,hour,uid_user_0,uid_user_1,uid_user_10,uid_user_11,uid_user_12,uid_user_13,uid_user_14,uid_user_15,...,labname_lab02,labname_lab03,labname_lab03s,labname_lab05s,labname_laba04,labname_laba04s,labname_laba05,labname_laba06,labname_laba06s,labname_project1
0,1,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,3,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,4,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,5,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1681,9,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1682,6,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1683,7,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1684,8,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1685,9,20,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [6]:
y = df['dayofweek']
y

0       4
1       4
2       4
3       4
4       4
       ..
1681    3
1682    3
1683    3
1684    3
1685    3
Name: dayofweek, Length: 1686, dtype: int64

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify = y, test_size=0.2, random_state=21)

In [8]:
y_test

1087    1
16      5
563     6
1381    3
1199    2
       ..
1411    3
1079    1
1222    2
1064    1
1243    2
Name: dayofweek, Length: 338, dtype: int64

 Обучите SVM, используя параметры, которые оказались лучшими в прошлом задании.
 В этот раз вам надо будет посчитать несколько метрик сразу: accuracy, precision, recall, ROC AUC.
precision и recall должны быть посчитаны для каждого класса (используйте average='weighted')ROC AUC должен быть посчитан для каждого класса против каждого другого класса (все возможные попарные комбинации) и после этого примените взвешенное среднее, чтобы получить финальное значение метрикирезультат работы кода должен выглядить так же, как пример ниже:

accuracy is 0.88757
precision is 0.89267
recall is 0.88757
roc_auc is 0.97878

In [10]:
svc = SVC(C = 10,
         class_weight = None,
         gamma = 'auto',
         kernel = 'rbf',
         random_state = 21,
         probability = True)
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)
y_pred_proba = svc.predict_proba(X_test)

In [12]:
print(f'accuracy is {accuracy_score(y_test, y_pred):.5f}\nprecision is {precision_score(y_test, y_pred, average = "weighted"):.5f}\nrecall is {recall_score(y_test, y_pred,average = "weighted"):.5f}\nroc_auc is {roc_auc_score(y_test, y_pred_proba, multi_class = "ovo", average = "weighted"):.5f}')

accuracy is 0.88757
precision is 0.89267
recall is 0.88757
roc_auc is 0.97878

   3. Decision tree
 
То же самое задание, но для дерева классификации

In [14]:
tree = DecisionTreeClassifier(class_weight = 'balanced',
         criterion = 'gini',
         max_depth = 21,
         random_state = 21)
tree.fit(X_train, y_train)
y_pred = tree.predict(X_test)
y_pred_proba = tree.predict_proba(X_test)

In [15]:
print(f'accuracy is {accuracy_score(y_test, y_pred):.5f}\nprecision is {precision_score(y_test, y_pred, average = "weighted"):.5f}\nrecall is {recall_score(y_test, y_pred,average = "weighted"):.5f}\nroc_auc is {roc_auc_score(y_test, y_pred_proba, multi_class = "ovo", average = "weighted"):.5f}')

accuracy is 0.89053
precision is 0.89402
recall is 0.89053
roc_auc is 0.93793

 4. Случайный лес
 
То же самое задание, но для дерева классификации

In [21]:
forest = RandomForestClassifier(class_weight = 'balanced',
         criterion = 'entropy',
         max_depth = 24,
         n_estimators = 100,
         random_state = 21)
forest.fit(X_train, y_train)
y_pred = forest.predict(X_test)
y_pred_proba = forest.predict_proba(X_test)

In [22]:
print(f'accuracy is {accuracy_score(y_test, y_pred):.5f}\nprecision is {precision_score(y_test, y_pred, average = "weighted"):.5f}\nrecall is {recall_score(y_test, y_pred,average = "weighted"):.5f}\nroc_auc is {roc_auc_score(y_test, y_pred_proba, multi_class = "ovo", average = "weighted"):.5f}')

accuracy is 0.93195
precision is 0.93402
recall is 0.93195
roc_auc is 0.98821

  5. Прогнозы
 
Выберите лучшую модель. Вы можете задаться вопросом, с точки зрения какой метрики, но при расчете вам станет всё очевидно.
Проанализируйте: для какого дня недели модель делает больше всего ошибок (в % от общего количество наблюдений этого класса в вашем датасете). 
Также проанализируйте на какой лаборатороной работе и на каком юзере модель делает больше всего ошибок уже вне зависимости от дней недели.
Сохраните модель.

Best model: Random Forest

In [23]:
for day in range(7):
    print(f'day : {day}, mistakes : {sum((y_test != forest.predict(X_test)) & (y_test == day))/sum(y_test == day)*100:.5f}%')

day : 0, mistakes : 22.22222%
day : 1, mistakes : 5.45455%
day : 2, mistakes : 6.66667%
day : 3, mistakes : 2.50000%
day : 4, mistakes : 14.28571%
day : 5, mistakes : 9.25926%
day : 6, mistakes : 2.81690%

Больше всего ошибок: понедельник

In [24]:
for column in X.columns:
    if 'user' in column:
        print(f'user:{column}, mistakes ', end = '')
        if len(X_test[X_test[column] == 1.0]) > 0:
            print(f'{1 - accuracy_score(y_test[X_test[column] == 1.0], forest.predict(X_test[X_test[column] == 1.0])):.3%}')
        else:
            print('not in list')

user:uid_user_0, mistakes not in list
user:uid_user_1, mistakes 0.000%
user:uid_user_10, mistakes 8.333%
user:uid_user_11, mistakes not in list
user:uid_user_12, mistakes 0.000%
user:uid_user_13, mistakes 0.000%
user:uid_user_14, mistakes 3.226%
user:uid_user_15, mistakes 0.000%
user:uid_user_16, mistakes 20.000%
user:uid_user_17, mistakes 0.000%
user:uid_user_18, mistakes 16.667%
user:uid_user_19, mistakes 10.526%
user:uid_user_2, mistakes 10.714%
user:uid_user_20, mistakes 0.000%
user:uid_user_21, mistakes 0.000%
user:uid_user_22, mistakes 0.000%
user:uid_user_23, mistakes 0.000%
user:uid_user_24, mistakes 9.091%
user:uid_user_25, mistakes 9.091%
user:uid_user_26, mistakes 0.000%
user:uid_user_27, mistakes 16.667%
user:uid_user_28, mistakes 0.000%
user:uid_user_29, mistakes 9.091%
user:uid_user_3, mistakes 14.286%
user:uid_user_30, mistakes 12.500%
user:uid_user_31, mistakes 11.111%
user:uid_user_4, mistakes 7.407%
user:uid_user_6, mistakes 50.000%
user:uid_user_7, mistakes not in list
user:uid_user_8, mistakes 0.000%

Больше всего ошибок: user_6

In [25]:
for column in X.columns:
    if 'labname' in column:
        print(f'labname:{column}, mistakes ', end = '')
        if len(X_test[X_test[column] == 1.0]) > 0:
            print(f'{1 - accuracy_score(y_test[X_test[column] == 1.0], forest.predict(X_test[X_test[column] == 1.0])):.3%}')
        else:
            print('not in list')

labname:labname_code_rvw, mistakes 7.692%
labname:labname_lab02, mistakes not in list
labname:labname_lab03, mistakes 100.000%
labname:labname_lab03s, mistakes 0.000%
labname:labname_lab05s, mistakes 16.667%
labname:labname_laba04, mistakes 17.143%
labname:labname_laba04s, mistakes 8.000%
labname:labname_laba05, mistakes 2.128%
labname:labname_laba06, mistakes 11.111%
labname:labname_laba06s, mistakes 6.667%
labname:labname_project1, mistakes 4.839%

Больше всего ошибок: labname_lab03

 6. Функция
 
Напишите функцию, которая принимает на вход список разных моделей и соответствующий модели список параметров в виде словаря. Функция возвращает словарь, который содержит все 4 метрики, расмотренных в этом задании, для каждой модели из списка. 
{'model1': {'accuracy': 0.7, 'precision': 0.5, ... },'model2': {...}}

In [29]:
def metrics(estimaters, params, X_train, y_train, X_test, y_test):
    result = dict()
    for i in range(len(estimaters)):
        estimater = estimaters[i].set_params(**params[i])
        estimater.fit(X_train, y_train)
        y_pred = estimater.predict(X_test)
        y_pred_proba = estimater.predict_proba(X_test)
        result['model' + str(i + 1)] = dict()
        result['model' + str(i + 1)]['accuracy'] = accuracy_score(y_test, y_pred)
        result['model' + str(i + 1)]['precision'] = precision_score(y_test, y_pred, average = "weighted")
        result['model' + str(i + 1)]['recall'] = recall_score(y_test, y_pred, average = "weighted")
        result['model' + str(i + 1)]['roc_auc'] = roc_auc_score(y_test, y_pred_proba, average = "weighted", multi_class = "ovo")
    return result

In [31]:
metrics([SVC(), DecisionTreeClassifier(), RandomForestClassifier()],
        [{'C' : 10,
         'class_weight' : None,
         'gamma' : 'auto',
         'kernel' : 'rbf',
         'random_state' : 21,
         'probability' : True},
        {'class_weight' : 'balanced',
        'criterion' : 'gini',
        'max_depth' : 21,
        'random_state' : 21},
        {'class_weight' : 'balanced',
        'criterion' : 'entropy',
        'max_depth' : 24,
         'n_estimators' : 100,
        'random_state' : 21}],
        X_train, y_train, X_test, y_test)

{'model1': {'accuracy': 0.8875739644970414,
  'precision': 0.8926729169690374,
  'recall': 0.8875739644970414,
  'roc_auc': 0.9787793228216216},
 'model2': {'accuracy': 0.8905325443786982,
  'precision': 0.8940158937843722,
  'recall': 0.8905325443786982,
  'roc_auc': 0.9379290651156622},
 'model3': {'accuracy': 0.9319526627218935,
  'precision': 0.9340183677910212,
  'recall': 0.9319526627218935,
  'roc_auc': 0.9882077759075321}}